### PR TITLE
✨#issue #483 has been solved ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
# 🚀 Pull Request

https://github.com/user-attachments/assets/cee6963e-b50e-4991-a612-66bad3287bc0

the X comes up when navbar is open and and other times its hamburger style.
@DharshiBalasubramaniyam can you please review this.
#issue #483 has been solved

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Actually we have several html files. So it is better to add the script to nav.js file. then automatically all the html files will be refected. Can you?

**Comment by T-Rahul-prabhu-38** [comment]
Ok I'll do it in sometime , I'm in clg rn

**Comment by T-Rahul-prabhu-38** [comment]
@DharshiBalasubramaniyam  the script tag has been added to a differnt page. please review this PR.

**Review by DharshiBalasubramaniyam — APPROVED** [review]
OKAY.

**Pull request merged**
