### PR TITLE
Updated the Contact Form Styling

### PR DESCRIPTION
**Pull request by RohanShrivastava08**
Here are some modifications I made in Contact Us section:
1. Background Color: Added a light pink background to the contact section.
2. Font Sizes: Increased the size a bit of heading.
3. Input Styles: Adjusted the padding, border radius, and hover effects for input fields and buttons.
4. Hover Effects: Added transition effects to the submit button and it changes color on hover.

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
@RohanShrivastava08,
Kindly mention the issue number which is assigned to you.

**Comment by RohanShrivastava08** [comment]
> @RohanShrivastava08, Kindly mention the issue number which is assigned to you.

I guess I got confused. Now I find the issues. i can pick issues which are in issues and which have GSSOC and Hacktoberfest tag. Am I Right?

**Comment by DharshiBalasubramaniyam** [comment]
> > @RohanShrivastava08, Kindly mention the issue number which is assigned to you.
> 
> I guess I got confused. Now I find the issues. i can pick issues which are in issues and which have GSSOC and Hacktoberfest tag. Am I Right?

Oh! No you have to work on the issues which are assigned to you. You can create your own issues in the repos. Wait until the admins or mentors assigned it to you. After assigning start working.

**Comment by DharshiBalasubramaniyam** [comment]
So the issue is not assigned to you right? 
I am closing this.
Kindly got through the rules and regulations of the program

**Pull request closed without merging**
