### PR TITLE
#284 Issue [Solved]:- Succesfully Modified Javascript of Navbar 

### PR DESCRIPTION
**Pull request by PrAyAg9**
Issue #284 Solved:

When i scroll down the home page now elements in navbar will change automatically Let me display it via video 
NOW:- 

https://github.com/user-attachments/assets/2a61263e-157c-437c-a32c-e7c7b74f487b

BEFORE:- if you scroll down nothing change in navbar . I fixed the bug in JS code when you had to change Instructionobserver Api threshold so it view all details and for click event listener to also listen scroll . Earlier error image:- 
image

### CODE REVIEW

**Comment by PrAyAg9** [comment]
I have used IntersectionObserver api in current JS as earlier one has the bug or that event listener only happens to listen on click and make change and now click event listener ensures that acticve class is toggled correctly, i am ready to make further changes. 
## Please verify the solution and reassign a level on it according to pull request. Thank you.

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Okay.... But why you remove the code snippets for mobile view of the nav andbottom to top button?

**Comment by PrAyAg9** [comment]
@DharshiBalasubramaniyam  ohh my bad, I didn't checked for responsiveness, Let me correct my mistake

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
