### PR TITLE
deleted repeated restaurants

### LINKED ISSUE #504: repetition of restaurants in dine-in
Various restaurants are repeated in the dine-in section.I want to fix this issue
Please assign this issue to me under gssoc-extd and hacktoberfest.

### LINKED ISSUE #506: change in privacy policy section
Screenshot 2024-10-13 at 11 44 10 PM

These points should be written in bullets or something.I want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

### PR DESCRIPTION
**Pull request by Kajalmehta29**
This pr fixes 2 issues. 

fixes #504 - level1
fixes #506 - level3

@Kajalmehta29 I am giving both 2 labels to this pr. But here after, kindly be careful when creating pr :)

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Please don't remove them. Instead you can replace those with new data.

**Comment by Kajalmehta29** [comment]
The data of restaurants is random or they exist? Then ill change accordingly.

**Comment by DharshiBalasubramaniyam** [comment]
> The data of restaurants is random or they exist? Then ill change accordingly.

random

**Review by DharshiBalasubramaniyam — COMMENTED** [review]
Why you updated the privacy page while It is not relevent to your issue?

**Comment by Kajalmehta29** [comment]
Hey @DharshiBalasubramaniyam  Privacy policy page updation was assigned to me only. I guess it commited here with this issue only. Both issues were assigned to me only.
Sorry for the confusion caused

**Comment by DharshiBalasubramaniyam** [comment]
That means 2 issues. So you have to create 2 seperate pr for each issue.

**Comment by Kajalmehta29** [comment]
Please merge this for 2 issues.

**Comment by Kajalmehta29** [comment]
Please merge this for 2 issues.

**Review by DharshiBalasubramaniyam — APPROVED** [review]
done!

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@MastanSayyad can you review this PR?

**Pull request merged**
