### PR TITLE
Added empty cart sidebar

### LINKED ISSUE #954: [Feat]: Add image for showing user cart is empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding image showing empty cart when user cart is empty, just in empty space above sentence as shown in screenshot.

Screenshot (70)

### Use Case

This will add user-friendly interactive effect to website.

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by shivanjalikarande**
# 🚀 Pull Request

## Description

Added sidebar for empty cart with visual appeal image & some friendly text to engage user when their cart is empty.

- Fixes #954 
- Closes #954

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

Screenshot (75)

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Nice! Going to give level 2. can you update this in other pages as well? blog, contributor, privacy, terms etc....

**Comment by DharshiBalasubramaniyam** [comment]
I need one more help from you.. In products page when searching items, it displays a text only. Can you add an image in that scenario as well? If you can, Dont commit  to this pr. You can create a seperate issue for this. Mention the issue no in this pr. Then I can assign it to you. AfterYou can start work.

**Comment by shivanjalikarande** [comment]
> Nice! Going to give level 2. can you update this in other pages as well? blog, contributor, privacy, terms etc....

Yes, @DharshiBalasubramaniyam  I will update for other pages as well

**Comment by shivanjalikarande** [comment]
> I need one more help from you.. In products page when searching items, it displays a text only. Can you add an image in that scenario as well? If you can, Dont commit to this pr. You can create a seperate issue for this. Mention the issue no in this pr. Then I can assign it to you. AfterYou can start work.

Yes @DharshiBalasubramaniyam, I have raised issue regarding this. Issue no: #984

**Comment by shivanjalikarande** [comment]
@DharshiBalasubramaniyam, I updated the code with required changes by adding content to all pages of website for empty cart. Please review this.

**Review by DharshiBalasubramaniyam — APPROVED** [review]
.

**Pull request merged**
