### PR TITLE
Added Small icons to the input fields of contact us box

### PR DESCRIPTION
**Pull request by BVPKARTHIKEYA**
Added small icons to the input fields of the contact us page!!
image
Hope you like it!!

### CODE REVIEW

**Comment by BVPKARTHIKEYA** [comment]
closes issue #337  @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts

**Comment by BVPKARTHIKEYA** [comment]
resolved!!
kindly approve my pr and close my issue!!

**Comment by DharshiBalasubramaniyam** [comment]
Hi @BVPKARTHIKEYA, I didn't think that placing icons like this is an good practice. Can you try similar to below one? 

image

If like you can create a new pr with above changes. I am closing this...

**Pull request closed without merging**
