### PR TITLE
add the same UI for privacy and terms and conditions and also added cursor

### LINKED ISSUE #765: Different UI for Terms conditions and privacy policy
Use same UI structure for both "Terms and conditions" and "privacy policy" pages. Currently both are different. 

image

image

You can use existing style of one of them or your own one.

### PR DESCRIPTION
**Pull request by Utkarsha156**
Fixes #765 
used the UI of terms and conditions for privacy as well and now both UI are same as you asked to do so
added cursor on privacy page 

Screenshot 2024-10-20 180232

### CODE REVIEW

**Comment by Utkarsha156** [comment]
@DharshiBalasubramaniyam please review the PR

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam please review the PR

Kindly resolve conflicts!

**Comment by Utkarsha156** [comment]
@DharshiBalasubramaniyam the conflicts have been resolved

**Comment by Utkarsha156** [comment]
you can merge the trial branch now @DharshiBalasubramaniyam or if any conflicts are still there let me know

**Pull request merged**
