### PR TITLE
Delivery form UI enhanced

### PR DESCRIPTION
**Pull request by charmi2109**
I have improved the user interface of the delivery section form. Previously, the input fields were excessively extended, which detracted from both the aesthetic and usability of the form.

In this redesign, I centered the form on the page and applied a transparent background, resulting in a modern and visually appealing appearance. This enhancement aims to increase interactivity, making it easier and more engaging for users to complete the form.

Fixes issue #919
Before:
image

After changes:
image

### CODE REVIEW

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Can you pls remove that bg image? The form is not clear.

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
.

**Comment by charmi2109** [comment]
Yes removed. Please check now.

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts

**Comment by DharshiBalasubramaniyam** [comment]
RC

**Comment by charmi2109** [comment]
Resolved conflicts. Please review

**Pull request merged**
