### PR TITLE
issue #25 closes (devxMani)

### PR DESCRIPTION
**Pull request by devxMani**
issue #25 closes

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
@devxMani, Please don't remove repeated locations. You can provide different location names as you wish.

**Comment by devxMani** [comment]
okkk i'll do it right now @DharshiBalasubramaniyam

**Comment by devxMani** [comment]
now you can add this PR i have added some

**Review by DharshiBalasubramaniyam — APPROVED** [review]

**Comment by DharshiBalasubramaniyam** [comment]
Thank you @devxMani.

**Pull request merged**
