### PR TITLE
solved issue #172

### PR DESCRIPTION
**Pull request by Devanshu1603**
Make the contact form input field reset after submitting a detail and also pop out a alert to let the user know that his/her details has been submitted. @DharshiBalasubramaniyam  Please look after the PR and merge it accordingly under gssoc-extended , hacktober fest , accepted and with appropriate level.

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
image

The form should submit only if all the inputs are valid. But when i am submitting the form with invalid input it still submitting. Check about that!

**Comment by Devanshu1603** [comment]
do you want me to apply checks like email format check or inputing only letter in name and numbers in phone-no

**Comment by Devanshu1603** [comment]
@DharshiBalasubramaniyam  i have added the validation check function . please review the changes and merge the PR accordingly.

**Comment by Devanshu1603** [comment]
@DharshiBalasubramaniyam  i have made the changes , please look after the pr and merge accordingly

**Comment by Devanshu1603** [comment]
@DharshiBalasubramaniyam  please look after my PR as i have added the suggested changes , and merge it accordingly.

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
