### PR TITLE
added search bar with dropdown for issue #130

### PR DESCRIPTION
**Pull request by BaraniVA**
This PR introduces a new search bar feature to the ice cream parlor website. The search bar allows users to search for ice cream flavors and displays a dropdown with suggestions as they type for #130 .

**Files added:**

**search.js**
-  Added an event listener for the search bar input to filter and display suggestions.
- Added a function to fetch suggestions based on the input.
- Implemented logic to show/hide the dropdown and style the search bar accordingly.
- Enhanced user interactions by updating the search bar value and hiding the dropdown when a suggestion is clicked.
- Ensured the dropdown styling does not change on focus if the input length is less than 1.

**search.css**
- Added styles for the search bar and dropdown.
- Styled the search bar with padding, font size, border, border-radius, and background color.
- Added a smooth transition for the border-radius.
- Styled the dropdown with custom scrollbar styles, positioning, background color, and border.
- Ensured the dropdown displays correctly when active and hides when not.

Files Modified:

**index.html**
- Added search bar, fav search icon and dropdown

**Testing**
Manually tested the search bar to ensure suggestions are displayed correctly.
Verified that clicking on a suggestion updates the search bar and hides the dropdown.

image

https://github.com/user-attachments/assets/05791225-8399-436e-bc4b-d9fa508665af

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Nice. The only thing is the search bar is not correctly visible in mobile view. Can you fix it? 

image

**Comment by DharshiBalasubramaniyam** [comment]
> Nice. The only thing is the search bar is not correctly visible in mobile view. Can you fix it? If you fix it, I can give level2 label for this pr.
> 
> image

**Comment by BaraniVA** [comment]
sure will change and update it now

**Comment by BaraniVA** [comment]
Hello @DharshiBalasubramaniyam added the changes to make the search bar to be visible in mobile view please check let me know for further changes..

https://github.com/user-attachments/assets/3fa2a209-b464-4b89-b110-b7b0c3f24378

**Review by BaraniVA — COMMENTED** [review]
Hi @DharshiBalasubramaniyam i changed the responsiveness for the search bar my apologies for the delay. thank you for your time and consideration

**Comment by DharshiBalasubramaniyam** [comment]
image

Entire website is crashed in the preview. Check it and create a new pr

**Pull request closed without merging**
