### PR TITLE
Added wishlist icon, wishlist side bar toggle, wishlist button in cards.

### LINKED ISSUE #689: [Feat]: Wishlist Page added
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Wishlist page should be added to allow customer to save their desired item for later use.

Wishlist Page Functionality
1.User Interface:
2.Functionality:Users can add items to their wishlist from product pages or during their shopping experience.
4.Conversion to Cart:Users should be able to easily move items from their wishlist to their shopping cart for checkout, streamlining the purchasing process.

@DharshiBalasubramaniyam kindly assign me this issue under GSSOC'24 ext. I will definitely make it a worthy contribution.

### Use Case

Use Cases
1.Future Purchases
2.Scenario: A customer browsing for softy flavour finds one they love but is currently unable to purchase it. They add it to their wishlist to consider later.
3.Benefit: The user can revisit the wishlist to analyze their options without needing to search for items again.

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no.#812
**Asking for extension of Issue #689** 
@DharshiBalasubramaniyam ma'am i'm breaking this issue in 2 parts.
It is part one in which i've added
1. Wishlist icon
2. Wishlist button on each card
3. Wishlist side toggle
4. Enhanced search bar designing

fixes #689

**Kindly mark this as level 2 at least, as it required a lot of changes to be done.**

**Searchbar Before:**
Screenshot 2024-10-19 071720

**Searchbar After:**
Screenshot 2024-10-19 071632

Screenshot 2024-10-19 071641

Screenshot 2024-10-19 071624

Screenshot 2024-10-19 000141

Do let me know if any further changes are required.

### CODE REVIEW

**Comment by NIKITABARANWAL890** [comment]
@DharshiBalasubramaniyam ma'am kindly review and merge this PR.

**Comment by NIKITABARANWAL890** [comment]
@DharshiBalasubramaniyam ma'am kindly look into it.

**Comment by NIKITABARANWAL890** [comment]
@DharshiBalasubramaniyam Ma'am, as contributors, we understand that you have a lot of work to manage. However, when PRs remain unmerged for 5-6 days, it can lower our motivation to continue contributing. We humbly request that you kindly review and merge our PRs at your earliest convenience.

Thank you,

**Comment by DharshiBalasubramaniyam** [comment]
@NIKITABARANWAL890 after merging your pr the products are not showing and in navbars the logo repeated twice.


Screenshot_20241024_063706_Chrome

Screenshot_20241024_064035_Chrome


Hence i am reverting your prs.

**Pull request merged**
