### PR TITLE
Login and Signup page ui updated

### LINKED ISSUE #334: Social icons and login form
I would like to improve the login form of your website under gssoc24-ext , their is a much better way of layouting the icons of google , facebook on the form of your website , please assign this issue to me and i will make sure to redesign it for a better user experience

### PR DESCRIPTION
**Pull request by Dipeshdahiya**
# 🚀 Pull Request

## Description

I have compressed the design and layout to make it more professional and good looking , please take a look on the new Ui based design of the pages

- Fixes #334
- Closes #334

## Type of Change

- [Yes ] Bug fix (non-breaking change which fixes an issue)
- [ Yes] New feature (non-breaking change which adds functionality)
- [ Yes] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ Yes] Documentation Update

## Checklist:

- [Yes ] My code follows the style guidelines of this project
- [Yes ] I have performed a self-review of my own code
- [ Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes ] I have made corresponding changes to the documentation
- [Yes ] My changes generate no new warnings
- [ Yes] I have added tests that prove my fix is effective or that my feature works
- [Yes ] New and existing unit tests pass locally with my changes
- [Yes] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-14 015341
Screenshot 2024-10-14 015419

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Same changes to do:
1. Remove login with Google button and signup with Google button.
2. Add the Google icon in the login page before face book (like in the sign up page)
3. Move "or" to top of the social icons.

Can you?

**Comment by Dipeshdahiya** [comment]
Screenshot 2024-10-15 000605
Screenshot 2024-10-15 000642

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Comment by Dipeshdahiya** [comment]
the score is not updated on the leaderboard for the PR, can you please help if possible

**Comment by DharshiBalasubramaniyam** [comment]
> the score is not updated on the leaderboard for the PR, can you please help if possible

Could you able to find it?

**Pull request merged**
