### PR TITLE
Spelling issue and spacing issue

### LINKED ISSUE #37: UI Enhancement: Improve Text Contrast, Icon Alignment
**Inconsistent Icons:** The phone and email icons are not aligned or styled uniformly. The up and down arrows next to the icons appear to be a rendering issue. Fixing these icons would provide a cleaner look.
**Icon Size and Spacing:** The social media icons are smaller compared to the text, and there’s inconsistent spacing between the icons and the corresponding text (e.g., Facebook, Instagram, Linkedin). Increasing the size of the icons and ensuring even spacing would improve balance.
**Uniformity in Labels:** The label for "Linkedin" should be corrected to "LinkedIn" (capitalize the 'I' to maintain brand name accuracy).
image
**Note:** I'd love to take on this issue and make the website look even cooler! Please assign it to me.

### PR DESCRIPTION
**Pull request by PremaDongare**
This PR changes the spelling issue as well as the spacing issue on the website.

solved
Fixes #37

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Hi @PremaDongare why app.html? What is that file do?

**Comment by PremaDongare** [comment]
Okk

**Comment by PremaDongare** [comment]
so sorry for app.html i was facing some issue in file so i copy the code to app.html .
so sorry for inconvinence next time i'll take care of this.

**Comment by DharshiBalasubramaniyam** [comment]
With app.html I cannot merge the pr.

**Comment by PremaDongare** [comment]
I can again copy the code to index.html

**Pull request closed without merging**
