### PR TITLE
Top scroll bar indicator Added in every html pages. 

### LINKED ISSUE #706: [Bug]: Top scroll bar indicator missing in several html pages
Add top scroll bar indicator in missing html files.

How to achive this.

in html body under preloader copy below code.

```
 <!-- scroll progress -->`
    <div class="scroll-progress"></div>
```

In header add css
`<link rel="stylesheet" href="styles/topscrollindicator.css">`

In body lastly add below script:
`<script src="script/topscrollindicator.js"></script>`

Kindy make sure the scroll bar is working in all pages.

### PR DESCRIPTION
**Pull request by Rohit72099**
# 🚀 Pull Request

## Description
Top scroll bar indicator Added in every html pages. 

- Fixes #706 
- Closes #706 

## Screenshot of final output/video
image

image
image
image
image

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
resolve conflicts.

**Comment by Rohit72099** [comment]
Ok

**Review by Rohit72099 — COMMENTED** [review]
reviewed

**Comment by Rohit72099** [comment]
image
Kindly help me with this, how to solve this.

**Pull request merged**
