### PR TITLE
Customized Cursor.

### PR DESCRIPTION
**Pull request by Amulya-B28**
I have changed the cursor which shows a pink arrow for hovering through out the website and a ice cream cursor when clicking buttons.

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Hi @Amulya-B28, Instead putting same style in all html files, remove those and put in the styles.css file. 

And Kindly remove using pinkicecream.png as cursor when hovering. use pink-arrow.png for entire site.

Can you do it?

**Comment by DharshiBalasubramaniyam** [comment]
And mention the issue number

**Comment by Amulya-B28** [comment]
yea sure ill remove it

**Review by Amulya-B28 — COMMENTED** [review]
i have changed cursor to pink arrow. Kindly review the changes mam

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Amulya-B28, Kindly resolve conflicts in index.html and update your branch.

**Comment by Amulya-B28** [comment]
I apologize for inconvenience caused by the mistakes I made in the recent code changes. This is my first time doing open source projects. Could you check the verify the changes made

**Comment by Amulya-B28** [comment]
Mam could you please review the changes.

**Comment by Amulya-B28** [comment]
Sorry to bother you again mam. Could you Please review the changes.

**Comment by Amulya-B28** [comment]
Sorry for bothering you @DharshiBalasubramaniyam mam but could you please review the changes made and accept my pull request.
issue : #125 
pull request: #155

**Comment by Amulya-B28** [comment]
@DharshiBalasubramaniyam I have updated the changes requested.

**Comment by Amulya-B28** [comment]
@DharshiBalasubramaniyam Mam i have got only few hours before this pull request is verified by Hacktoberfest....can you please merge this. Thank you. Looking for a positive response @DharshiBalasubramaniyam 

issue : #125
pull request: #155

**Comment by DharshiBalasubramaniyam** [comment]
There are so many conflicts. And you have repeated same style code in all the files. Instead you can put it in styles.css file. Because that file was added in all the html files. 

Kindly create a new pr. I am closing this

**Pull request closed without merging**
