### PR TITLE
Shorter and Centerly aligned Input fields

### LINKED ISSUE #563: Too long input section
Screenshot 2024-10-15 005244
Screenshot 2024-10-15 005325
input sections are too big , we can make it short and centre aligned to make it look beautiful.

### PR DESCRIPTION
**Pull request by Roshn1**
# 🚀 Pull Request #563 

## Description
I have change the alignment of the input areas of two html file.

- Fixes #563
- Closes #(issue Number)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-16 012314
Screenshot 2024-10-16 012322

### CODE REVIEW

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
the ui is not looking good in mobile view. Can you check it? And kindly remive inline styles and put them in styles.css

image

**Comment by Roshn1** [comment]
> # 🚀 Pull Request #563
> ## Description
> I have change the alignment of the input areas of two html file.
> 
> * Fixes [Too long input section #563](https://github.com/DharshiBalasubramaniyam/ice-cream-parlour-website/issues/563)
> * Closes #(issue Number)
> 
> ## Type of Change
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation Update
> 
> ## Checklist:
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  New and existing unit tests pass locally with my changes
> * [ ]  Any dependent changes have been merged and published in downstream modules
> 
> ## Screenshot of final output/video
> Screenshot 2024-10-16 012314 Screenshot 2024-10-16 012322


The task which you have assigned , I have completed it . Please recheck once.

**Comment by Roshn1** [comment]
Any updates?

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts.

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts and create new pr.

**Pull request closed without merging**
