### PR TITLE
Add Hover Effects to Why IcyCo? Section

### PR DESCRIPTION
**Pull request by neeru24**
This pull request implements hover effects for the "Why IcyCo?" section to enhance user interaction and visual appeal. The following changes have been made:
fixes: #511 

**Changes Made**

- Hover Effects: Added background color change and scale transformation to .feature-box on hover.
- Icon Rotation: Introduced a slight rotation for icons within .icon-circle on hover.
- Text Color Change: Changed the text color for the heading and paragraph on hover for better visibility.

These enhancements aim to create a more engaging user experience by providing visual feedback when users interact with the "Why IcyCo?" section. This can help improve user retention and satisfaction.

### CODE REVIEW

**Review by DharshiBalasubramaniyam — APPROVED** [review]
The ui is collapsed. can you check it:

before:
image

Your one:
image

can you check it?

**Comment by neeru24** [comment]
Give me some time please. I'll fix it

**Comment by neeru24** [comment]
@DharshiBalasubramaniyam Hi, I've fixed it. Now the UI is not getting collapsed. Kindly review and merge these changes.

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
