### PR TITLE
social links updated

### PR DESCRIPTION
**Pull request by WednesdaySP**
https://github.com/user-attachments/assets/f22afeb4-2f45-406d-8343-79df357dcb00

### CODE REVIEW

**Comment by WednesdaySP** [comment]
fixed #238

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Kindly resolve conflicts!

**Comment by WednesdaySP** [comment]
@DharshiBalasubramaniyam  conflicts resolved, could you please add level label also

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
