### PR TITLE
Feat: Added placeholder in contact us form

### LINKED ISSUE #533: placeholder in Contact Us page
there is no placeholder in input box i want to add the placeholder to it

Screenshot 2024-10-14 164054

### PR DESCRIPTION
**Pull request by harjasae2001**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

- Fixes #533 
- Closes #533 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
{20B15981-2425-4469-9FC6-969D6A807D74}

### CODE REVIEW

**Comment by harjasae2001** [comment]
@DharshiBalasubramaniyam pls review my PR

**Comment by harjasae2001** [comment]
@sanjay-kv @dharmesh191312 @ArchanRD @milansamuel609 pls review my PR

**Comment by DharshiBalasubramaniyam** [comment]
The issue is not assigned to you!

**Comment by harjasae2001** [comment]
I know this was not assigned to me but pls don't mark this as invalid. You can check I requested many times to assign me that issue. But mistakenly i submitted the PR without knowing i was not assigned this one.Can u pls merge my PR.

**Pull request closed without merging**
