### PR TITLE
Main image is changed now (no water mark and improved image)

### LINKED ISSUE #39: Improved Main Image (that contains water mark)
I can replace and provide a similar or better graphics image for the main home page that has an Ice Cream Image. The Image has water mark that can be clearly seen and does not looks good. 
Screenshot 2024-10-02 104911

### PR DESCRIPTION
**Pull request by Muskan-bhatt249**
Please review, I have changed the main image on home screen to be without water mark and a better one. Thank you for providing chance to contribute. 

fixes #39

### CODE REVIEW

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam  #39 issue (I created that issue and was assigned to me) this is the PR, please close that once this is accepted.

**Comment by DharshiBalasubramaniyam** [comment]
fixes #39

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
There is no changes in the image in the website. Still watermark exists. Kindly check once again

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam I replaced the image with new file added by me named Hero1 , I will check once again Thank You.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam I replaced the image with new file added by me named Hero1 , I will check once again Thank You.

Replace current image with the new one in index.html

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
image

The image is too small that before

**Comment by Muskan-bhatt249** [comment]
Yes I am working on it

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam Please Check now if the changes are visible now.

**Comment by DharshiBalasubramaniyam** [comment]
image

Image was not visible @Muskan-bhatt249. It was not necessary to the same image that i had used. You may use any other image from the internet

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam I added a different picture only, and in my system it is showing like this still. I don't understand what mistake I am making in updating the code
Screenshot (754)

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam sorry for bothering so much, I have updated it please check.

**Comment by Muskan-bhatt249** [comment]
@DharshiBalasubramaniyam Do I need to make any changes??

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
