### PR TITLE
Added password meter

### LINKED ISSUE #302: Add a responsive password strength meter during sign-up.
I want to add a responsive password strength level meter which can display user's password strength when they are signing up.

It does.,
Display password strength to users as they create their passwords.
Improve user privacy by encouraging stronger passwords.
Enhance user experience with real-time feedback.

I'm working in gssoc extended. Please provide me suitable labels.

### PR DESCRIPTION
**Pull request by PavanTeja2005**
# 🚀 Pull Request

## Description

I have added a responsive and neat password strength meter.
It blends with the theme beautifully and is greatly responsive..

- Fixes #302 
- Closes #302

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

image

image

image

### CODE REVIEW

**Comment by PavanTeja2005** [comment]
@DharshiBalasubramaniyam Done

**Comment by PavanTeja2005** [comment]
It shows five levels and uses zxcvbn libarary. 
very weak
weak
okay
good
strong

**Comment by PavanTeja2005** [comment]
@DharshiBalasubramaniyam please assign suitable labels and merge

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
