### PR TITLE
Adding scrolling animation. #440 

### PR DESCRIPTION
**Pull request by vijaychandra1910**
Adding some scroll animation please review and merge.

### CODE REVIEW

**Comment by vijaychandra1910** [comment]
Screenshot 2024-10-13 232635
Screenshot 2024-10-13 232647
@DharshiBalasubramaniyam please check it.

**Comment by DharshiBalasubramaniyam** [comment]
Mention your issue number. Follow pr templete.

**Comment by vijaychandra1910** [comment]
#440 this is issue number @DharshiBalasubramaniyam

**Comment by vijaychandra1910** [comment]
why it is showing conflict yesterday it was not showing.

**Comment by vijaychandra1910** [comment]
please Mark level 2 badge as shown in my issue.

**Pull request merged**
