### PR TITLE
Spacing done, slight color change done , font style and size changed

### LINKED ISSUE #28: Change Compressed Fonts for Better Readability
I’ve noticed that the current font on the website appears a bit compressed, which can make reading challenging. However, I love the overall design and think a few enhancements could significantly improve readability and user engagement. With some adjustments, we can make the site even more eye-catching and accessible for all users!
image
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

### PR DESCRIPTION
**Pull request by Mehtarishita**
All done 
Kindly merge the request

closes #28 
image

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Mehtarishita, Mention your assigned issue number

**Comment by Mehtarishita** [comment]
#199

**Comment by Mehtarishita** [comment]
Any changes needed?
Kindly merge.

**Comment by Mehtarishita** [comment]
@DharshiBalasubramaniyam kindly merge.
if changes needed let me knw.

**Comment by adarshsingh0103** [comment]
@Mehtarishita   Can you please! assign me to work on this issue.

**Review by DharshiBalasubramaniyam — COMMENTED** [review]
image

UI is not looking good i think. Check and create a new pr.

**Pull request closed without merging**
