### PR TITLE
Added Template & fixed the preloader time

### LINKED ISSUE #67: Adding issue and PR Templates
- making style adjustment for FAQ section
- adding templates for raising issue and raising PR with label for gssoc, feature, documentation, improvement & required tags
- level tag will be leaved as its owner authority!

### PR DESCRIPTION
**Pull request by Khushalsarode**
closes #67

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Khushalsarode Kindly remove the preloader adjustments. Those changes are not required and not related to your issue.

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Hi @Khushalsarode Kindly remove the preloader adjustments. Those changes are not required and not related to your issue.

**Comment by Khushalsarode** [comment]
> Hi @Khushalsarode Kindly remove the preloader adjustments. Those changes are not required and not related to your issue.

Sure

**Comment by Khushalsarode** [comment]
@DharshiBalasubramaniyam  changes reverted as requested!

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
