### PR TITLE
Fixed #223: Integrate Chatbot named FrostyGuide

### LINKED ISSUE #223: Chatbot Integration
### Feature: Chatbot Integration

**Objective**: 
Integrate a chatbot to assist users with:
- Navigating product options (flavors, sizes, prices).
- Answering FAQs (store hours, locations).
- Offering customer support or redirecting users to contact options.

**Implementation**:
I propose using Dialogflow for chatbot integration, with intents for product navigation, FAQs, and support. It will be embedded in `index.html` and styled to match the existing UI.

**Request for Assignment**:
Kindly assign this issue to me for contribution under GSSoC-extd and Hacktoberfest 2024.

### PR DESCRIPTION
**Pull request by BigBang001**
# 🚀 Pull Request

### Chatbot Integration:
- Added the FrostyGuide chatbot to assist users with:
  - Navigating product options such as flavors, sizes, and prices.
  - Answering common FAQs regarding store hours, locations, and more.
  - Providing customer support with redirection to appropriate contact options.

### UI Enhancements:
- Adjusted the scroll-to-top button to avoid overlapping with the chatbot widget, ensuring a seamless user experience.
- Matched chatbot styling with the existing site layout for consistent design.

### Testing & Validation:
- Conducted thorough testing of chatbot functionality and interaction flows.
- Verified that all UI elements work harmoniously across devices and screen sizes.

### Additional Notes:
- Resolved existing minor conflicts between UI components to improve overall site performance and accessibility.

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
dont create pr before assigning.

**Comment by DharshiBalasubramaniyam** [comment]
Mention your issue number

**Comment by BigBang001** [comment]
Hi @DharshiBalasubramaniyam 

I have updated the Pull Request with the respective Issue Number.

**Comment by BigBang001** [comment]
Hi @DharshiBalasubramaniyam 

Can you review the pull request as I have made the changes?

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts!

**Comment by BigBang001** [comment]
Hi @DharshiBalasubramaniyam 

I have resolved the conflicts.

**Review by DharshiBalasubramaniyam — APPROVED** [review]

**Pull request merged**
