### PR TITLE
resolve the submit and reset btn

### PR DESCRIPTION
**Pull request by adityalaxkar123**
title : bug

issue: submit and reset btn not working.

Section: on island-wide-delivery feature.

solution: added the feature onclick the submit btn shows the message of submitted succesfully and auto reset the form and onclick the reset btn it reset the form.

### CODE REVIEW

**Comment by adityalaxkar123** [comment]
my issue no. is #287

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts

**Comment by adityalaxkar123** [comment]
Conflicts resolved @DharshiBalasubramaniyam

**Comment by adityalaxkar123** [comment]
This assignment remove by mistake sorry

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
