### PR TITLE
icons added

### LINKED ISSUE #616: useful links
image
 i will add icons to all of them in above image please assign@DharshiBalasubramaniyam

### PR DESCRIPTION
**Pull request by abhi200446**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.
succesfully added suitable icons for quick links please label gssoc ext and hactoberfest accepted @DharshiBalasubramaniyam
- Fixes #(issue Number)
- #779
- Closes #(issue Number)
Fixes #616 
## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
image

### CODE REVIEW

**Comment by abhi200446** [comment]
issue number #779

**Comment by DharshiBalasubramaniyam** [comment]
> issue number #779

This is your pr number. Did you create an issue in this repo regarding this?

**Comment by abhi200446** [comment]
yes @DharshiBalasubramaniyam

**Comment by abhi200446** [comment]
can you please reply about the work done by me the work is completed which you assigned @DharshiBalasubramaniyam  bruh

**Comment by DharshiBalasubramaniyam** [comment]
> yes @DharshiBalasubramaniyam

If you created an issue. then mention that issue number. Then only i can close that issue.

**Comment by abhi200446** [comment]
my issue number is #616  @DharshiBalasubramaniyam  can you please tell me why you have not merged about the work done by me

**Pull request merged**
