### PR TITLE
changed the bg of login html and added css

### LINKED ISSUE #301: Sign in page is not  too good or we can add some background related to site ...its not looking attractive
can you assign me this part.
and add gssoc ext
Screenshot 2024-10-08 233302

### PR DESCRIPTION
**Pull request by shruti9935**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

- Fixed #301 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-18 162943
this is what i  have made the changes
Screenshot 2024-10-18 162857
this is before how it looks like

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Resolve conflicts

**Comment by shruti9935** [comment]
@DharshiBalasubramaniyam all conflicts are resolved kindly
kindly merge the pr

**Comment by shruti9935** [comment]
Hello PR
I resolved the conflicts kindly look into it and merge the pr
Thankyou

**Review by DharshiBalasubramaniyam — APPROVED** [review]
.

**Pull request merged**
