### PR TITLE
Feature/image round issue #362

### LINKED ISSUE #362: Improv the UI of index.html make the product images fit the theme
### Description 
The images of the product have corners while the outer box is curvy os it looks little disorienting also make the images corner curvy so it looks correct 

### issue image

374678130-e247a7be-102e-40ea-bce0-fd8dbf5a6023 (1)

As you can see the corner should be fixed 

Please assign me this issue under gssoc and hackfest

### PR DESCRIPTION
**Pull request by Anujyadav0074**
374826664-5fefff94-b0a0-4bc5-9d9e-1212df2555d3

Image has been rounded and i have checked everything is working fine 

fixes #362

### CODE REVIEW

**Comment by Anujyadav0074** [comment]
I have also changed the roundness of border so they look a little better because 10 was not looking that good

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
All good. But mention your issue number.

**Comment by Anujyadav0074** [comment]
sorry i put it in the title here is the issue no "#362"

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
