### PR TITLE
Added functionality to wishlist button 

### LINKED ISSUE #812: [Feat]: Add wishlist icon, wishlist side bar toggle, wishlist button in cards.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding
1.Wishlist icon
2.Wishlist button on each card
3.Wishlist side toggle
4.Enhanced search bar designing

@DharshiBalasubramaniyam kindly assign this to me.

### Use Case

It will add more features to the website

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no. #689 
Ma'am
**Kindly mark it as level 3 as you told me earlier** 

fixes #812 

Changes done:
1.Functionality:Users can add items to their wishlist from product pages.
2.Conversion to Cart:Users should be able to easily move items from their wishlist to their shopping cart for checkout, streamlining the purchasing process.
3.Remove or add item from wishlist.

Uploading Screen Recording 2024-10-19 074824.mp4…

Uploading Screen Recording 2024-10-19 074824.mp4…

Kindly mark this as level 3, as it required significant effort to implement this functionality. Any further adjustments are welcome.

### CODE REVIEW

**Comment by NIKITABARANWAL890** [comment]
@DharshiBalasubramaniyam ma'am kindly review and merge this PR.

**Comment by DharshiBalasubramaniyam** [comment]
@NIKITABARANWAL890, kindly check your issue #689. I asked you to raise 2 issues. Did you raise?

**Comment by NIKITABARANWAL890** [comment]
> @NIKITABARANWAL890, kindly check your issue #689. I asked you to raise 2 issues. Did you raise?

Oh i'm so sorry ma'am, i raised 2 issues but it got deleted somehow, i'm extremely sorry for the inconvinience.
I've raised the issue, can you please assign and merge it now?

**Comment by NIKITABARANWAL890** [comment]
ma'am kindly look into it.

**Comment by DharshiBalasubramaniyam** [comment]
@NIKITABARANWAL890 Resolve conflicts!

**Comment by NIKITABARANWAL890** [comment]
> @NIKITABARANWAL890 Resolve conflicts!

Done

**Pull request merged**
