### PR TITLE
added search  bar in navbar

### LINKED ISSUE #1009: we Need to search Icon in Navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

he search icon is easy to locate at the top of the page, making it simple for customers to quickly search for what they need, especially if they already know the product or category they’re interested in.

ith quick access to search, users can navigate directly to products without needing to explore multiple menus or categories, creating a smoother and more efficient browsing experience.
Screenshot (462)

### Use Case

The search icon allows the customer to type in the product name directly, quickly finding it without navigating multiple pages, streamlining repeat purchases.

### Benefits

Quick Access: The search icon provides immediate access to the search function, enabling users to find products quickly without navigating through multiple menus.

Improved User Experience: Simplifies the shopping process by allowing customers to directly search for items, enhancing overall site usability and satisfaction.

Increased Product Discovery: Encourages users to explore a broader range of products by entering keywords or phrases, leading to potential upselling and cross-selling opportunities.

Higher Conversion Rates: Users who utilize the search function often have stronger purchase intent, which can lead to increased sales and reduced cart abandonment rates.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by RahulPrasadYadav**
# 🚀 Pull Request

## Description
added search bar in the home page .. we can easily search any product in home page 

- Fixes #1009 
- Closes #1009 

## Type of Change

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

Screenshot (464)

### CODE REVIEW

**Comment by RahulPrasadYadav** [comment]
@DharshiBalasubramaniyam merged this

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
is this responsive? and resolve conflicts...

**Comment by RahulPrasadYadav** [comment]
> is this responsive? and resolve conflicts...

complete

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
image
 The website is totally crashed in the preview. Kindly check it out.

**Pull request closed without merging**
