### PR TITLE
UI fix

### LINKED ISSUE #477: Change the ui of the reviews section in index.html
The ui: 
image

### PR DESCRIPTION
**Pull request by mishraRj**
This pull request addresses the issue related to the UI of the review section on the ICYCO website. The primary changes include:

Improved Layout: Redesigned the review boxes to create a more visually appealing layout, with three review boxes displayed per row.
Enhanced Styles: Updated styles for better responsiveness and aesthetics, including background colors, borders, and hover effects.
Mobile Responsiveness: Adjusted styles to ensure that the review section is fully responsive on different screen sizes.
Related Issue:
This PR addresses the issue regarding the UI of the review section as referenced in the issue tracker.

- Fixes #477 
- Closes #477 

## Changed Swiper into fixed layot in review section

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/1f6b7468-4b60-4acc-87bc-01133212bbf1

### CODE REVIEW

**Comment by mishraRj** [comment]
the color scheme will be same (pink color) as in main repo... This was just a sample video.

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Why do you remove the contact section from the home page?

**Comment by mishraRj** [comment]
> Why do you remove the contact section from the home page?

Sry it removed by mistake... I am gonna correct this.

**Comment by DharshiBalasubramaniyam** [comment]
Remove conflicts!

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Why contact section s in black color. 

image

**Comment by mishraRj** [comment]
> Why contact section s in black color.
> 
> image


Can you tell me the way to test my codes for your repo on my pc ? I was not able to test this issue.
Although I can remove black color from contact section but I think it got issue from dark theme I set before, because I was working on both issues on same time in different branches.

Plz suggest me a way to test changes on your page from my pc. That would be so better and I am so close to final results.

**Comment by mishraRj** [comment]
> Why contact section s in black color.
> 
> image

I have fixed the UI Completely.

https://github.com/user-attachments/assets/47c9df56-cf1d-4252-a205-7a5f295af16c

**Review by DharshiBalasubramaniyam — APPROVED** [review]
done!

**Pull request merged**
