### PR TITLE
Completely fixed Dark Theme toggle feature to all pages of website.

### PR DESCRIPTION
**Pull request by mishraRj**
@DharshiBalasubramaniyam 
# 🚀 Pull Request

## Description
This pull request addresses the implementation and enhancement of the dark theme toggle feature across all pages of the website. Users can now seamlessly switch between light and dark modes, providing a more customizable and accessible user experience.

Changes Made:
Dark Theme Toggle Implementation: Integrated a toggle switch that allows users to switch between dark and light themes.
Styling Adjustments: Updated styles to ensure that all text, backgrounds, and elements display correctly in both light and dark modes.
Local Storage Persistence: Implemented local storage functionality to remember the user's theme preference across sessions.

- Fixes #(issue Number)
- Closes #(issue Number)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/62a239e6-f857-471d-97b2-18f1a1386c28

### CODE REVIEW

**Comment by mishraRj** [comment]
This branch has conflicts because I set dark theme according to new future UI which will merge after some time. I request you to review my issue #518  before this issue. This branch will have less or no conflicts after merging of UI_Fix branch.

**Comment by DharshiBalasubramaniyam** [comment]
This pr is not needed.

**Comment by mishraRj** [comment]
> This pr is not needed.

ok no problem :)

**Comment by mishraRj** [comment]
Should i delete this branch now ?

**Pull request closed without merging**
