### PR TITLE
Changed the loader

### LINKED ISSUE #588: Change the loader style
The present loader is good but we can make it more visually appealing by replacing it by a flavour wheel. This loader will consist of a spinning wheel with different ice cream flavor sections. 
@DharshiBalasubramaniyam

### PR DESCRIPTION
**Pull request by Abankita**
# 🚀 Pull Request

## Description
I have replaced the existing preloader with a circular ice cream flavor-themed loader featuring eight animated flavors. I designed this circular loader to display different ice cream flavors in a visually appealing way, providing a fun and engaging preloading experience. I have changed it for all the pages.

- Fixes #588
- Closes #588

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot (80)
Drive link for video:
https://drive.google.com/file/d/16u3pYIgsvOgqTqqcEkUGkeD245kzFiug/view?usp=drivesdk

### CODE REVIEW

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam Can you please review this PR? Any suggestions or feedback is highly welcomed.
Thank you!

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam Glad that you merged my PR. Can you please add the necessary labels too?

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam can you please add the necessary labels too? 
Thank you!

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam please add level label. 
Thank you!

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam It seems like you have missed to assign me labels. Can you please do that? Thanks for understanding!

**Pull request merged**
