### PR TITLE
Added cursor trail

### PR DESCRIPTION
**Pull request by rounakdey6**
Uploading Screen Recording 2024-10-15 122233.mp4…

here is the look #538

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Your screenshot is not visible. and resolve conflicts!

**Comment by rounakdey6** [comment]
https://github.com/user-attachments/assets/5e89d49f-f175-4da7-8094-10c9c591a0dd

@DharshiBalasubramaniyam i have resolved the conflicts , have a look

**Comment by rounakdey6** [comment]
@DharshiBalasubramaniyam please level the hacktoberfest

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
You have repeated same code in all html files. Instead add the style to styles.css, create new script file for cursor under scripts folder and add that file in all html files

**Comment by rounakdey6** [comment]
@DharshiBalasubramaniyam okay , & please level it hacktoberfest

**Pull request closed without merging**
