### PR TITLE
Cart UI modification

### LINKED ISSUE #751: enhance cart ui
I would like change the ui of the cart cards.

current:
image

expected:
image
The category name is not needed.

### PR DESCRIPTION
**Pull request by mehendisil2004**
# 🚀 Pull Request

## Description

This changes has been done only in the product page to review it. This changes can be separately done to all pages. Do let me know your views.

- Fixes #751 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-20 124211

### CODE REVIEW

**Comment by mehendisil2004** [comment]
@DharshiBalasubramaniyam please merge the PR

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam please merge the PR

Resolve conflicts!

**Comment by mehendisil2004** [comment]
> > @DharshiBalasubramaniyam please merge the PR
> 
> Resolve conflicts!

Done

**Review by DharshiBalasubramaniyam — APPROVED** [review]
Done!

**Pull request merged**
