### PR TITLE
Issue  # 157 - Improve Sign-In Page Design and Security features

### PR DESCRIPTION
**Pull request by Prabh-84**
Enchance UI of Signin And Sign up Also added password toggle button to hide characters
 before the sign in page looks like this 
WhatsApp Image 2024-10-06 at 23 39 16_89b466bd
 
 After enhancing the UI  and toggle button it looks like 
 
WhatsApp Image 2024-10-06 at 23 01 23_337c9725

in the same way Signup page UI is also enhanced according to website look

signuppage ui design

please check it    , Mam I have solved issuse # 157  Improve Sign-In Page Design and Sercurity features@DharshiBalasubramaniyam

### CODE REVIEW

**Comment by Prabh-84** [comment]
@DharshiBalasubramaniyam   Mam please look into the PR  on issuse Issue # 157 - Improve Sign-In Page Design and Security features   @mansiruhil13

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-08 232519
current design of login or signup page already done. no need for this issue

**Comment by Prabh-84** [comment]
@mansiruhil13 i dont think so it was the login or signup page of ice - cream -parlour website , it is from some ther project

**Review by DharshiBalasubramaniyam — COMMENTED** [review]
Kindly resolve conflicts and create  a nee pr.

**Comment by Prabh-84** [comment]
@DharshiBalasubramaniyam mam i cant find any conflicts ,  can you explain breifly what are the conflicts that i have to resolve

**Pull request closed without merging**
