### PR TITLE
#600 Search Bar Added

### PR DESCRIPTION
**Pull request by Yash-Jadaun**
# 🚀 Pull Request

## Description
I added a Search bar in website. @DharshiBalasubramaniyam plz merge my pr.

- Fixes #(600)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
Screenshot (1153)

## Screenshot of final output/video

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
#600

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
The ui is not looking good. Can you improve it.

**Comment by Yash-Jadaun** [comment]
Yes Offcourse I will improve the UI. @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Create a new pr.

**Pull request closed without merging**
