### PR TITLE
Changed spelling  Issue No#860

### PR DESCRIPTION
**Pull request by Garima-149**
@DharshiBalasubramaniyam Please merge this with appropriate labels.

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
Mention your issue number.

**Comment by Garima-149** [comment]
Yes I have mentioned it 
Issue no #860

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Why have you done so many changes in product_database.js and product.js. These are not relevent to your issue? Can you pls remove them?

**Comment by Garima-149** [comment]
@DharshiBalasubramaniyam Actuallly,I did some spacing initially in those pages and it is showing that only.
And talking about product_database.js file ,then I have assigned one more issue later on #887 in this project so I later on commit the changes for it and unknowingly it got merged with these changes.
But these extra changes will not affect the site wrongly. I will create a different pull request for issue no #887 .
Please merge it so that I can make  other PR'S  for other assigned issues.

**Comment by Garima-149** [comment]
@DharshiBalasubramaniyam please reply

**Pull request closed without merging**
