### PR TITLE
Updated colors, hover effects, padding/margins, and added icon transition

### PR DESCRIPTION
**Pull request by eshitatalukdar08**
#314 
I have made some significant changes to the FAQs section. The changes include:

(i) Changed the background and font colors, padding, and margin of the question section.
(ii) Altered the background and font colors, padding, and margin of the answer section.
(iii) Made adjustments to the hovering effects.
(iv) Added a transition to the dropdown icon.
(v) Adjusted the width of the question and answer bars.
(vi) Added font weight to h2.
(vii) Modified the margin between the question and answer sections.

I hope you will like the changes I made.

### CODE REVIEW

**Comment by eshitatalukdar08** [comment]
Hello @DharshiBalasubramaniyam please accept my pull request

**Review by DharshiBalasubramaniyam — CHANGES_REQUESTED** [review]
Done!

**Comment by eshitatalukdar08** [comment]
Thank you so much 😊

**Comment by eshitatalukdar08** [comment]
I could not understand can you please elaborate?

**Comment by eshitatalukdar08** [comment]
Can you please label it as level 2 as I have really tried to make the FAQs section look good also in one push?

**Comment by eshitatalukdar08** [comment]
I have also tried to use complimentary colours to give a pop effect.
Screenshot 2024-10-11 234940

**Pull request merged**
